In [47]:
using DrWatson
@quickactivate "MEngProject"
using MEngProject, CUDA, DifferentialEquations, PyPlot, NNlib,  ImageFiltering, Images, MEngProject, MEngProject.LamKernels, MEngProject.Laminart, MEngProject.Utils, BenchmarkTools, Test

┌ Error: Failed to revise /mnt/storage_1/users/cullinanen/.julia/dev/MEngProject.jl/src/LaminartGPU.jl
│   exception = (LoadError("/mnt/storage_1/users/cullinanen/.julia/dev/MEngProject.jl/src/LaminartGPU.jl", 1292, "missing comma or ) in argument list"), Union{Ptr{Nothing}, Base.InterpreterIP}[Ptr{Nothing} @0x00007fa6cf68b433])
└ @ Revise /mnt/storage_1/users/cullinanen/.julia/packages/Revise/BqeJF/src/Revise.jl:760
┌ Warning: Due to a previously reported error, the running code does not match saved version for the following files:
│ 
│   /mnt/storage_1/users/cullinanen/.julia/dev/MEngProject.jl/src/LaminartGPU.jl
│ 
│ Use Revise.errors() to report errors again.
└ @ Revise /mnt/storage_1/users/cullinanen/.julia/packages/Revise/BqeJF/src/Revise.jl:820
┌ Warning: Due to a previously reported error, the running code does not match saved version for the following files:
│ 
│   /mnt/storage_1/users/cullinanen/.julia/dev/MEngProject.jl/src/LaminartGPU.jl
│ 
│ Use Revise.errors() to report e

In [48]:
function reshape2d_4d(img::AbstractArray)
    reshape(img, size(img)[1], size(img)[2], 1, 1)
end

┌ Warning: Due to a previously reported error, the running code does not match saved version for the following files:
│ 
│   /mnt/storage_1/users/cullinanen/.julia/dev/MEngProject.jl/src/LaminartGPU.jl
│ 
│ Use Revise.errors() to report errors again.
└ @ Revise /mnt/storage_1/users/cullinanen/.julia/packages/Revise/BqeJF/src/Revise.jl:820
┌ Warning: Due to a previously reported error, the running code does not match saved version for the following files:
│ 
│   /mnt/storage_1/users/cullinanen/.julia/dev/MEngProject.jl/src/LaminartGPU.jl
│ 
│ Use Revise.errors() to report errors again.
└ @ Revise /mnt/storage_1/users/cullinanen/.julia/packages/Revise/BqeJF/src/Revise.jl:820


reshape2d_4d (generic function with 1 method)

In [23]:
img = convert(Array{Float32,2}, load(datadir("Iine_100_100_gs.png")));
img = reshape2d_4d(img)
# img = cu(img)
r = similar(img)

p = LaminartGPU.kernels_(img, Parameters.parameters);

LaminartGPU.I_u!(r, img, p)
temp_out = (I = img, r = r)
p = merge(p, temp_out);

In [24]:
# tspan = (0.0f0, 5f0)
# u0 = cu(reshape(zeros(Float32, p.dim_i, p.dim_j*(5*p.K+2)), p.dim_i, p.dim_j, 5*p.K+2,1));

In [25]:
tspan = (0.0f0, 5f0)
u0 = reshape(zeros(Float32, p.dim_i, p.dim_j*(5*p.K+2)), p.dim_i, p.dim_j, 5*p.K+2,1);

In [26]:
arr1 = u0[:, :, 1:p.K,:]
arr2 = u0[:, :, 1:1,:];

In [27]:
f = LaminartGPU.LamFunction_cpu(
    similar(arr1), # x
    similar(arr1), # y
    similar(arr1), # m
    similar(arr1), # z
    similar(arr1), # s
    similar(arr2), # v_p
    similar(arr2), # v_m
    similar(arr1), # dx
    similar(arr1), # dy
    similar(arr1), # dm
    similar(arr1), # dz
    similar(arr1), # ds
    similar(arr2), # dv_p
    similar(arr2), # dv_m
    similar(arr2), # x_lgn
    similar(arr1), # C
    similar(arr1), # H_z
    similar(arr2), # V_temp1
    similar(arr2), # V_temp2
    similar(arr1), # Q_temp
    similar(arr1), # P_temp
    );

In [28]:
prob= ODEProblem(f, u0, tspan, p);

In [ ]:
sol = solve(prob)

In [29]:
sys = modelingtoolkitize(prob)

KeyError: KeyError: key 'K' not found

In [6]:
a = @view u0[:,:,1:2,:]

100×100×2×1 view(::CuArray{Float32,4,Nothing}, :, :, 1:2, :) with eltype Float32:
[:, :, 1, 1] =
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0

In [7]:
b = @views u0[:,:,1:2,:]

100×100×2×1 view(::CuArray{Float32,4,Nothing}, :, :, 1:2, :) with eltype Float32:
[:, :, 1, 1] =
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0

In [9]:
typeof(a)== typeof(b)

true

In [10]:
a == b

┌ Warning: Performing scalar operations on GPU arrays: This is very slow, consider disallowing these operations with `allowscalar(false)`
└ @ GPUArrays /mnt/storage_1/users/cullinanen/.julia/packages/GPUArrays/4W5rW/src/host/indexing.jl:43


true

In [17]:
@variables u[1:100,1:100,1:12,1:1]
@parameters t
@derivatives D'~t
du = simplify.(f(D(u),u,p,0.0))

MethodError: MethodError: Cannot `convert` an object of type Array{Operation,4} to an object of type Expression
Closest candidates are:
  convert(::Type{Expression}, !Matched::Operation) at /mnt/storage_1/users/cullinanen/.julia/packages/ModelingToolkit/fM618/src/utils.jl:24
  convert(::Type{Expression}, !Matched::Expression) at /mnt/storage_1/users/cullinanen/.julia/packages/ModelingToolkit/fM618/src/utils.jl:20
  convert(::Type{Expression}, !Matched::Bool) at /mnt/storage_1/users/cullinanen/.julia/packages/ModelingToolkit/fM618/src/utils.jl:22
  ...

In [19]:
D(u[1,1,1,1])

derivative(u₁ˏ₁ˏ₁ˏ₁, t)

In [20]:

u

100×100×12×1 Array{Operation,4}:
[:, :, 1, 1] =
   u₁ˏ₁ˏ₁ˏ₁    u₁ˏ₂ˏ₁ˏ₁    u₁ˏ₃ˏ₁ˏ₁    u₁ˏ₄ˏ₁ˏ₁  …    u₁ˏ₉₉ˏ₁ˏ₁    u₁ˏ₁₀₀ˏ₁ˏ₁
   u₂ˏ₁ˏ₁ˏ₁    u₂ˏ₂ˏ₁ˏ₁    u₂ˏ₃ˏ₁ˏ₁    u₂ˏ₄ˏ₁ˏ₁       u₂ˏ₉₉ˏ₁ˏ₁    u₂ˏ₁₀₀ˏ₁ˏ₁
   u₃ˏ₁ˏ₁ˏ₁    u₃ˏ₂ˏ₁ˏ₁    u₃ˏ₃ˏ₁ˏ₁    u₃ˏ₄ˏ₁ˏ₁       u₃ˏ₉₉ˏ₁ˏ₁    u₃ˏ₁₀₀ˏ₁ˏ₁
   u₄ˏ₁ˏ₁ˏ₁    u₄ˏ₂ˏ₁ˏ₁    u₄ˏ₃ˏ₁ˏ₁    u₄ˏ₄ˏ₁ˏ₁       u₄ˏ₉₉ˏ₁ˏ₁    u₄ˏ₁₀₀ˏ₁ˏ₁
   u₅ˏ₁ˏ₁ˏ₁    u₅ˏ₂ˏ₁ˏ₁    u₅ˏ₃ˏ₁ˏ₁    u₅ˏ₄ˏ₁ˏ₁       u₅ˏ₉₉ˏ₁ˏ₁    u₅ˏ₁₀₀ˏ₁ˏ₁
   u₆ˏ₁ˏ₁ˏ₁    u₆ˏ₂ˏ₁ˏ₁    u₆ˏ₃ˏ₁ˏ₁    u₆ˏ₄ˏ₁ˏ₁  …    u₆ˏ₉₉ˏ₁ˏ₁    u₆ˏ₁₀₀ˏ₁ˏ₁
   u₇ˏ₁ˏ₁ˏ₁    u₇ˏ₂ˏ₁ˏ₁    u₇ˏ₃ˏ₁ˏ₁    u₇ˏ₄ˏ₁ˏ₁       u₇ˏ₉₉ˏ₁ˏ₁    u₇ˏ₁₀₀ˏ₁ˏ₁
   u₈ˏ₁ˏ₁ˏ₁    u₈ˏ₂ˏ₁ˏ₁    u₈ˏ₃ˏ₁ˏ₁    u₈ˏ₄ˏ₁ˏ₁       u₈ˏ₉₉ˏ₁ˏ₁    u₈ˏ₁₀₀ˏ₁ˏ₁
   u₉ˏ₁ˏ₁ˏ₁    u₉ˏ₂ˏ₁ˏ₁    u₉ˏ₃ˏ₁ˏ₁    u₉ˏ₄ˏ₁ˏ₁       u₉ˏ₉₉ˏ₁ˏ₁    u₉ˏ₁₀₀ˏ₁ˏ₁
  u₁₀ˏ₁ˏ₁ˏ₁   u₁₀ˏ₂ˏ₁ˏ₁   u₁₀ˏ₃ˏ₁ˏ₁   u₁₀ˏ₄ˏ₁ˏ₁      u₁₀ˏ₉₉ˏ₁ˏ₁   u₁₀ˏ₁₀₀ˏ₁ˏ₁
  u₁₁ˏ₁ˏ₁ˏ₁   u₁₁ˏ₂ˏ₁ˏ₁   u₁₁ˏ₃ˏ₁ˏ₁   u₁₁ˏ₄ˏ₁ˏ₁  …   u₁₁ˏ₉₉ˏ₁ˏ₁   u₁₁ˏ₁₀₀ˏ₁ˏ₁
  u₁₂ˏ₁ˏ₁ˏ₁   u₁₂ˏ₂ˏ₁ˏ₁   u₁₂ˏ₃ˏ₁ˏ₁   u₁₂ˏ₄ˏ₁ˏ₁      u₁₂ˏ₉₉ˏ₁ˏ₁   u₁₂ˏ₁₀₀ˏ₁ˏ₁
  u₁₃ˏ₁ˏ₁ˏ₁   u₁

In [8]:
sys = modelingtoolkitize(prob)

UndefVarError: UndefVarError: modelingtoolkitize not defined

In [30]:
# function modelingtoolkitize(prob::DiffEqBase.ODEProblem)
#     prob.f isa DiffEqBase.AbstractParameterizedFunction &&
#                             return (prob.f.sys, prob.f.sys.states, prob.f.sys.ps)
    @parameters t
   

(t,)

In [31]:
 vars = reshape([Variable(:x, i)(t) for i in eachindex(prob.u0)],size(prob.u0))
   

100×100×12×1 Array{Operation,4}:
[:, :, 1, 1] =
   x₁(t)  x₁₀₁(t)  x₂₀₁(t)  x₃₀₁(t)  …  x₉₇₀₁(t)  x₉₈₀₁(t)   x₉₉₀₁(t)
   x₂(t)  x₁₀₂(t)  x₂₀₂(t)  x₃₀₂(t)     x₉₇₀₂(t)  x₉₈₀₂(t)   x₉₉₀₂(t)
   x₃(t)  x₁₀₃(t)  x₂₀₃(t)  x₃₀₃(t)     x₉₇₀₃(t)  x₉₈₀₃(t)   x₉₉₀₃(t)
   x₄(t)  x₁₀₄(t)  x₂₀₄(t)  x₃₀₄(t)     x₉₇₀₄(t)  x₉₈₀₄(t)   x₉₉₀₄(t)
   x₅(t)  x₁₀₅(t)  x₂₀₅(t)  x₃₀₅(t)     x₉₇₀₅(t)  x₉₈₀₅(t)   x₉₉₀₅(t)
   x₆(t)  x₁₀₆(t)  x₂₀₆(t)  x₃₀₆(t)  …  x₉₇₀₆(t)  x₉₈₀₆(t)   x₉₉₀₆(t)
   x₇(t)  x₁₀₇(t)  x₂₀₇(t)  x₃₀₇(t)     x₉₇₀₇(t)  x₉₈₀₇(t)   x₉₉₀₇(t)
   x₈(t)  x₁₀₈(t)  x₂₀₈(t)  x₃₀₈(t)     x₉₇₀₈(t)  x₉₈₀₈(t)   x₉₉₀₈(t)
   x₉(t)  x₁₀₉(t)  x₂₀₉(t)  x₃₀₉(t)     x₉₇₀₉(t)  x₉₈₀₉(t)   x₉₉₀₉(t)
  x₁₀(t)  x₁₁₀(t)  x₂₁₀(t)  x₃₁₀(t)     x₉₇₁₀(t)  x₉₈₁₀(t)   x₉₉₁₀(t)
  x₁₁(t)  x₁₁₁(t)  x₂₁₁(t)  x₃₁₁(t)  …  x₉₇₁₁(t)  x₉₈₁₁(t)   x₉₉₁₁(t)
  x₁₂(t)  x₁₁₂(t)  x₂₁₂(t)  x₃₁₂(t)     x₉₇₁₂(t)  x₉₈₁₂(t)   x₉₉₁₂(t)
  x₁₃(t)  x₁₁₃(t)  x₂₁₃(t)  x₃₁₃(t)     x₉₇₁₃(t)  x₉₈₁₃(t)   x₉₉₁₃(t)
       ⋮                             ⋱    

In [38]:
 params =  reshape([Variable(i)() for i in eachindex(prob.p)],size(prob.p))
  

MethodError: MethodError: no method matching size(::NamedTuple{(:K, :δ_v, :δ_c, :δ_m, :δ_z, :δ_s, :σ_1, :C_1, :C_2, :σ_2, :γ, :α, :ϕ, :Γ, :v_21, :μ, :ν, :n, :att, :η_p, :η_m, :λ, :a_23_ex, :a_23_in, :v12_6, :v12_4, :ψ, :C_AB_l, :H_σ_x, :H_σ_y, :H_fact, :H_l, :T_fact, :T_p_m, :T_v2_fact, :H_size, :W_size, :lgn_equ_u, :lgn_equ_A, :lgn_equ_B, :filling, :W_l, :k_gauss_1, :k_gauss_2, :k_C_d, :k_C_b, :k_x_lgn, :k_W_p, :k_W_m, :k_H, :k_T_p, :k_T_m, :k_T_p_v2, :k_T_m_v2, :dim_i, :dim_j, :x_V2, :ν_pw_n, :I, :r),Tuple{Int64,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Int64,Float32,Float32,Float32,Int64,Array{Float32,1},Float32,Float32,Int64,Int64,Float32,Float32,Float32,String,Int64,CuArray{Float32,4,Nothing},CuArray{Float32,4,Nothing},CuArray{Float32,4,Nothing},CuArray{Float32,4,Nothing},CuArray{Float32,4,Nothing},CuArray{Float32,4,Nothing},CuArray{Float32,4,Nothing},CuArray{Float32,4,Nothing},CuArray{Float32,4,Nothing},CuArray{Float32,4,Nothing},CuArray{Float32,4,Nothing},CuArray{Float32,4,Nothing},Int64,Int64,CuArray{Float32,4,Nothing},Float32,CuArray{Float32,4,Nothing},CuArray{Float32,4,Nothing}}})
Closest candidates are:
  size(!Matched::BitArray{1}) at bitarray.jl:99
  size(!Matched::BitArray{1}, !Matched::Integer) at bitarray.jl:103
  size(!Matched::Core.Compiler.StmtRange) at show.jl:1845
  ...

In [32]:
 params =  reshape([Variable(:α,i)() for i in eachindex(collect(keys(prob.p)))],size(collect(keys(prob.p))))
  

60-element Array{Operation,1}:
  α₁
  α₂
  α₃
  α₄
  α₅
  α₆
  α₇
  α₈
  α₉
 α₁₀
 α₁₁
 α₁₂
 α₁₃
   ⋮
 α₄₉
 α₅₀
 α₅₁
 α₅₂
 α₅₃
 α₅₄
 α₅₅
 α₅₆
 α₅₇
 α₅₈
 α₅₉
 α₆₀

In [37]:
Variable(:α,1,1)

α₁ˏ₁

In [31]:
typeof(prob.p)

NamedTuple{(:K, :δ_v, :δ_c, :δ_m, :δ_z, :δ_s, :σ_1, :C_1, :C_2, :σ_2, :γ, :α, :ϕ, :Γ, :v_21, :μ, :ν, :n, :att, :η_p, :η_m, :λ, :a_23_ex, :a_23_in, :v12_6, :v12_4, :ψ, :C_AB_l, :H_σ_x, :H_σ_y, :H_fact, :H_l, :T_fact, :T_p_m, :T_v2_fact, :H_size, :W_size, :lgn_equ_u, :lgn_equ_A, :lgn_equ_B, :filling, :W_l, :k_gauss_1, :k_gauss_2, :k_C_d, :k_C_b, :k_x_lgn, :k_W_p, :k_W_m, :k_H, :k_T_p, :k_T_m, :k_T_p_v2, :k_T_m_v2, :dim_i, :dim_j, :x_V2, :ν_pw_n, :I, :r),Tuple{Int64,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Float32,Int64,Float32,Float32,Float32,Int64,Array{Float32,1},Float32,Float32,Int64,Int64,Float32,Float32,Float32,String,Int64,CuArray{Float32,4,Nothing},CuArray{Float32,4,Nothing},CuArray{Float32,4,Nothing},CuArray{Float32,4,Nothing},CuArray{Float32,4,Nothing},CuArray{Float32,4,Nothing},CuArray{Float32,4,Nothing},CuArray{Float32,4

In [35]:
for i in eachindex(prob.p)
    println(i)
end

K
δ_v
δ_c
δ_m
δ_z
δ_s
σ_1
C_1
C_2
σ_2
γ
α
ϕ
Γ
v_21
μ
ν
n
att
η_p
η_m
λ
a_23_ex
a_23_in
v12_6
v12_4
ψ
C_AB_l
H_σ_x
H_σ_y
H_fact
H_l
T_fact
T_p_m
T_v2_fact
H_size
W_size
lgn_equ_u
lgn_equ_A
lgn_equ_B
filling
W_l
k_gauss_1
k_gauss_2
k_C_d
k_C_b
k_x_lgn
k_W_p
k_W_m
k_H
k_T_p
k_T_m
k_T_p_v2
k_T_m_v2
dim_i
dim_j
x_V2
ν_pw_n
I
r


In [40]:
collect(keys(prob.p))

60-element Array{Symbol,1}:
 :K
 :δ_v
 :δ_c
 :δ_m
 :δ_z
 :δ_s
 :σ_1
 :C_1
 :C_2
 :σ_2
 :γ
 :α
 :ϕ
 ⋮
 :k_W_m
 :k_H
 :k_T_p
 :k_T_m
 :k_T_p_v2
 :k_T_m_v2
 :dim_i
 :dim_j
 :x_V2
 :ν_pw_n
 :I
 :r

In [34]:
params = p

(K = 2, δ_v = 1.25f0, δ_c = 0.25f0, δ_m = 0.01875f0, δ_z = 0.125f0, δ_s = 2.5f0, σ_1 = 1.0f0, C_1 = 1.5f0, C_2 = 0.075f0, σ_2 = 0.5f0, γ = 10.0f0, α = 0.5f0, ϕ = 2.0f0, Γ = 0.2f0, v_21 = 0.0f0, μ = 2.0f0, ν = 1.1f0, n = 6.0f0, att = 0.0f0, η_p = 2.1f0, η_m = 1.5f0, λ = 1.5f0, a_23_ex = 3.0f0, a_23_in = 0.5f0, v12_6 = 1.0f0, v12_4 = 5.0f0, ψ = 0.5f0, C_AB_l = 5, H_σ_x = 3.0f0, H_σ_y = 4.0f0, H_fact = 5.0f0, H_l = 19, T_fact = Float32[0.87, 0.13], T_p_m = 0.302f0, T_v2_fact = 0.625f0, H_size = 19, W_size = 19, lgn_equ_u = 1.0f0, lgn_equ_A = 0.0f0, lgn_equ_B = 0.0f0, filling = "circular", W_l = 19, k_gauss_1 = Float32[0.0029690173 0.013306212 … 0.013306212 0.0029690173; 0.013306212 0.059634306 … 0.059634306 0.013306212; … ; 0.013306212 0.059634306 … 0.059634306 0.013306212; 0.0029690173 0.013306212 … 0.013306212 0.0029690173], k_gauss_2 = Float32[6.9624775f-8 2.808864f-5 … 2.808864f-5 6.9624775f-8; 2.808864f-5 0.011331766 … 0.011331766 2.808864f-5; … ; 2.808864f-5 0.011331766 … 0.01133176

In [36]:
  @derivatives D'~t

    rhs = [D(var) for var in vars]

   

100×100×12×1 Array{Operation,4}:
[:, :, 1, 1] =
   derivative(x₁(t), t)  derivative(x₁₀₁(t), t)  …   derivative(x₉₉₀₁(t), t)
   derivative(x₂(t), t)  derivative(x₁₀₂(t), t)      derivative(x₉₉₀₂(t), t)
   derivative(x₃(t), t)  derivative(x₁₀₃(t), t)      derivative(x₉₉₀₃(t), t)
   derivative(x₄(t), t)  derivative(x₁₀₄(t), t)      derivative(x₉₉₀₄(t), t)
   derivative(x₅(t), t)  derivative(x₁₀₅(t), t)      derivative(x₉₉₀₅(t), t)
   derivative(x₆(t), t)  derivative(x₁₀₆(t), t)  …   derivative(x₉₉₀₆(t), t)
   derivative(x₇(t), t)  derivative(x₁₀₇(t), t)      derivative(x₉₉₀₇(t), t)
   derivative(x₈(t), t)  derivative(x₁₀₈(t), t)      derivative(x₉₉₀₈(t), t)
   derivative(x₉(t), t)  derivative(x₁₀₉(t), t)      derivative(x₉₉₀₉(t), t)
  derivative(x₁₀(t), t)  derivative(x₁₁₀(t), t)      derivative(x₉₉₁₀(t), t)
  derivative(x₁₁(t), t)  derivative(x₁₁₁(t), t)  …   derivative(x₉₉₁₁(t), t)
  derivative(x₁₂(t), t)  derivative(x₁₁₂(t), t)      derivative(x₉₉₁₂(t), t)
  derivative(x₁₃(t), t)  der

In [38]:
#  if DiffEqBase.isinplace(prob)
        lhs = similar(vars, Any)
       

100×100×12×1 Array{Any,4}:
[:, :, 1, 1] =
 #undef  #undef  #undef  #undef  #undef  …  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef     #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef     #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef     #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef     #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef  …  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef     #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef     #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef     #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef     #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef  …  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef     #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef     #undef  #undef

In [39]:
 prob.f(lhs, vars, params, t)
#     else
#         lhs = prob.f(vars, params, t)
#     end

   

MethodError: MethodError: no method matching Float32(::Operation)
Closest candidates are:
  Float32(::T) where T<:Number at boot.jl:715
  Float32(!Matched::Int8) at float.jl:60
  Float32(!Matched::Int16) at float.jl:60
  ...

In [37]:
 DiffEqBase.isinplace(prob)

true

In [24]:
 eqs = vcat([rhs[i] ~ lhs[i] for i in eachindex(prob.u0)]...)
    de = ODESystem(eqs,t,vec(vars),vec(params))

    de
end

KeyError: KeyError: key 'K' not found

In [25]:
prob.p.K

2

In [26]:
prob.p

(K = 2, δ_v = 1.25f0, δ_c = 0.25f0, δ_m = 0.01875f0, δ_z = 0.125f0, δ_s = 2.5f0, σ_1 = 1.0f0, C_1 = 1.5f0, C_2 = 0.075f0, σ_2 = 0.5f0, γ = 10.0f0, α = 0.5f0, ϕ = 2.0f0, Γ = 0.2f0, v_21 = 0.0f0, μ = 2.0f0, ν = 1.1f0, n = 6.0f0, att = 0.0f0, η_p = 2.1f0, η_m = 1.5f0, λ = 1.5f0, a_23_ex = 3.0f0, a_23_in = 0.5f0, v12_6 = 1.0f0, v12_4 = 5.0f0, ψ = 0.5f0, C_AB_l = 5, H_σ_x = 3.0f0, H_σ_y = 4.0f0, H_fact = 5.0f0, H_l = 19, T_fact = Float32[0.87, 0.13], T_p_m = 0.302f0, T_v2_fact = 0.625f0, H_size = 19, W_size = 19, lgn_equ_u = 1.0f0, lgn_equ_A = 0.0f0, lgn_equ_B = 0.0f0, filling = "circular", W_l = 19, k_gauss_1 = Float32[0.0029690173 0.013306212 … 0.013306212 0.0029690173; 0.013306212 0.059634306 … 0.059634306 0.013306212; … ; 0.013306212 0.059634306 … 0.059634306 0.013306212; 0.0029690173 0.013306212 … 0.013306212 0.0029690173], k_gauss_2 = Float32[6.9624775f-8 2.808864f-5 … 2.808864f-5 6.9624775f-8; 2.808864f-5 0.011331766 … 0.011331766 2.808864f-5; … ; 2.808864f-5 0.011331766 … 0.01133176

In [27]:
p

(K = 2, δ_v = 1.25f0, δ_c = 0.25f0, δ_m = 0.01875f0, δ_z = 0.125f0, δ_s = 2.5f0, σ_1 = 1.0f0, C_1 = 1.5f0, C_2 = 0.075f0, σ_2 = 0.5f0, γ = 10.0f0, α = 0.5f0, ϕ = 2.0f0, Γ = 0.2f0, v_21 = 0.0f0, μ = 2.0f0, ν = 1.1f0, n = 6.0f0, att = 0.0f0, η_p = 2.1f0, η_m = 1.5f0, λ = 1.5f0, a_23_ex = 3.0f0, a_23_in = 0.5f0, v12_6 = 1.0f0, v12_4 = 5.0f0, ψ = 0.5f0, C_AB_l = 5, H_σ_x = 3.0f0, H_σ_y = 4.0f0, H_fact = 5.0f0, H_l = 19, T_fact = Float32[0.87, 0.13], T_p_m = 0.302f0, T_v2_fact = 0.625f0, H_size = 19, W_size = 19, lgn_equ_u = 1.0f0, lgn_equ_A = 0.0f0, lgn_equ_B = 0.0f0, filling = "circular", W_l = 19, k_gauss_1 = Float32[0.0029690173 0.013306212 … 0.013306212 0.0029690173; 0.013306212 0.059634306 … 0.059634306 0.013306212; … ; 0.013306212 0.059634306 … 0.059634306 0.013306212; 0.0029690173 0.013306212 … 0.013306212 0.0029690173], k_gauss_2 = Float32[6.9624775f-8 2.808864f-5 … 2.808864f-5 6.9624775f-8; 2.808864f-5 0.011331766 … 0.011331766 2.808864f-5; … ; 2.808864f-5 0.011331766 … 0.01133176

In [42]:
f(lhs, vars, params, t)

┌ Warning: Slow fallback implementation invoked for conv!  You probably don't want this; check your datatypes.
│   yT = Expression
│   T1 = Operation
│   T2 = Float32
└ @ NNlib /mnt/storage_1/users/cullinanen/.julia/packages/NNlib/sSn9M/src/conv.jl:206


MethodError: MethodError: no method matching Expression(::Int64)
Closest candidates are:
  Expression(::T) where T<:Number at boot.jl:715
  Expression(!Matched::Bool) at /mnt/storage_1/users/cullinanen/.julia/packages/ModelingToolkit/fM618/src/utils.jl:26
  Expression(!Matched::Base.TwicePrecision) where T<:Number at twiceprecision.jl:243
  ...

In [40]:
arr1 = vars[:, :, 1:p.K,:]

arr2 = vars[:, :, 1:1,:];

In [41]:
f = LaminartGPU.LamFunction_cpu(
    similar(arr1), # x
    similar(arr1), # y
    similar(arr1), # m
    similar(arr1), # z
    similar(arr1), # s
    similar(arr2), # v_p
    similar(arr2), # v_m
    similar(arr1), # dx
    similar(arr1), # dy
    similar(arr1), # dm
    similar(arr1), # dz
    similar(arr1), # ds
    similar(arr2), # dv_p
    similar(arr2), # dv_m
    similar(arr2), # x_lgn
    similar(arr1), # C
    similar(arr1), # H_z
    similar(arr2), # V_temp1
    similar(arr2), # V_temp2
    similar(arr1), # Q_temp
    similar(arr1), # P_temp
    );

In [28]:
prob= ODEProblem(f, u0, tspan, p);

In [46]:
NNlib.conv!(f.x_lgn, f.x, p.k_x_lgn, NNlib.DenseConvDims(f.x, p.k_x_lgn, padding=0, flipkernel=true))

┌ Warning: Slow fallback implementation invoked for conv!  You probably don't want this; check your datatypes.
│   yT = Operation
│   T1 = Operation
│   T2 = Float32
└ @ NNlib /mnt/storage_1/users/cullinanen/.julia/packages/NNlib/sSn9M/src/conv.jl:206


UndefRefError: UndefRefError: access to undefined reference

In [45]:
 cdim = NNlib.DenseConvDims(f.x, p.k_x_lgn, padding=0, flipkernel=true)

DenseConvDims: (100, 100, 2) * (1, 1) -> (100, 100, 1), stride: (1, 1), pad: (0, 0, 0, 0), dil: (1, 1), flip: true